### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by dlarue** [drwilco/RTL8822BU#1]
I have removed my built-in wifi card(mini-PCIe) to add an external eGPU and while I could get the rtl8822 driver running with 17.10, my main OS is still 16.04 and kernel 4.4.x  so your fixes saved me. Thank you.

The AC1200 also seems rather fast so I might end up getting one for a couple of the rPi 2's I have around and now I know what driver source to use!

**Comment by drwilco** [comment]
You're welcome!
